### ISSUE TITLE
Pop-up windows during aviary installation

### ISSUE THREAD

**Issue by h1he2li3** [OpenMDAO/om-Aviary#33]
### Description

I was following the instructions on Aviary installation. I tried to use testflo . & then during the run, i get all these pop-up windows that appear and disappear by themselves. I was not sure if it is a bug or something else or (hopefully not) some virus in my computer. I have attached the screenshot.

### Example

testflo .

### Aviary Version

0.9.0

### Relevant environment information

![Screenshot 2024-01-05 at 07 28 22](https://github.com/OpenMDAO/om-Aviary/assets/109512410/3628f395-3c8a-4dba-9e1d-d2d7a9606a83)

**Comment by Kenneth-T-Moore** [comment]
This happens on OSX sometimes when you create a new virtual environment with anaconda or venv, because the OS doesn't recognize it as a secure executable. You will just need to sign the application using `codesign`; the process is described here:

https://stackoverflow.com/questions/19688841/add-python-application-to-accept-incoming-network-connections
